Updates dev setup script

diff --git a/osx_setup/dev_setup b/osx_setup/dev_setup
--- a/osx_setup/dev_setup
+++ b/osx_setup/dev_setup
@@ -1,10 +1,14 @@
 #!/bin/bash
+
+## end setup on fail
+set -e
+
 echo "Installing Homebrew"
 ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
 clear
 
 echo "Installing awscli, nodejs, python, ruby, cask, php-cs-fixer"
-brew install awscli nodejs python ruby cask php-cs-fixer
+brew install --force awscli nodejs python ruby cask php-cs-fixer
 
 echo "Installing Compass"
 sudo gem install compass
@@ -15,8 +19,8 @@ echo "Install nodemon, forever and grunt"
 sudo npm install -g nodemon forever grunt grunt-cli
 clear
 
-echo "Install mysqlworkbench, google drive, dropbox, firefox, chrome, sublime text, atom, spotify, office and Grammarly"
-brew cask install --force mysqlworkbench firefox google-chrome google-backup-and-sync dropbox sublime-text atom grammarly spotify slack skype microsoft-office postman
+echo "Install mysqlworkbench, google drive, dropbox, firefox, chrome, sublime text, atom, spotify, cyberduck, office and Grammarly"
+brew cask install --force mysqlworkbench firefox google-chrome google-backup-and-sync dropbox sublime-text atom grammarly spotify slack skype microsoft-office postman cyberduck adobe-creative-cloud
 clear
 
 brew doctor
